name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.8  # Update to your required version

    - name: Initialize Terraform
      run: terraform init

    - name: Check Terraform Formatting
      run: terraform fmt -check -recursive

    - name: Validate Terraform Configuration
      run: terraform validate

    - name: Plan Terraform Deployment
      run: terraform plan
